// Regenerates internal/api/web/emoji.mjs from Unicode emoji-test.txt and the
// CLDR English annotations that supply search keywords.
//
//   node tools/gen-emoji.mjs
//
// Emoji newer than MAX_VERSION are skipped because shipping fonts render them
// as tofu, which is worse than not offering them at all.

import { writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";

const MAX_VERSION = 15.1;
const SOURCES = {
  test: "https://www.unicode.org/Public/emoji/latest/emoji-test.txt",
  annotations:
    "https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/cldr-annotations-full/annotations/en/annotations.json",
  derived:
    "https://raw.githubusercontent.com/unicode-org/cldr-json/main/cldr-json/cldr-annotations-derived-full/annotationsDerived/en/annotations.json",
};

async function get(url) {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`${url}: ${response.status}`);
  return response.text();
}

const [testData, annotationsData, derivedData] = await Promise.all(
  Object.values(SOURCES).map(get),
);
const keywords = {
  ...JSON.parse(derivedData).annotationsDerived.annotations,
  ...JSON.parse(annotationsData).annotations.annotations,
};

const LINE =
  /^([0-9A-F ]+?)\s*;\s*fully-qualified\s*#\s*(\S+)\s+E(\d+\.\d+)\s+(.+)$/;
const groups = [];
let group = "",
  subgroup = "";
for (const line of testData.split("\n")) {
  const groupMatch = /^# group:\s*(.+)$/.exec(line);
  if (groupMatch) {
    group = groupMatch[1].trim();
    groups.push({ name: group, emoji: [] });
    continue;
  }
  const subgroupMatch = /^# subgroup:\s*(.+)$/.exec(line);
  if (subgroupMatch) {
    subgroup = subgroupMatch[1].trim();
    continue;
  }
  const match = LINE.exec(line);
  if (!match) continue;
  const [, , emoji, version, name] = match;
  if (Number(version) > MAX_VERSION) continue;
  if (/skin tone/.test(name)) continue;
  if (group === "Component") continue;
  const words = (value) =>
    value
      .toLowerCase()
      .split(/[^\p{L}\p{N}+]+/u)
      .filter((term) => term.length > 1 || /[+\d]/.test(term));
  // The name is searched on its own, so only keywords it does not already
  // contain are worth the bytes.
  const named = new Set(words(name));
  const terms = new Set(
    words(
      [subgroup.replace(/-/g, " "), ...(keywords[emoji]?.default || [])].join(
        " ",
      ),
    ).filter((term) => !named.has(term)),
  );
  groups.at(-1).emoji.push([emoji, name, [...terms].sort().join(" ")]);
}

const kept = groups.filter((entry) => entry.emoji.length);
const total = kept.reduce((sum, entry) => sum + entry.emoji.length, 0);
// One tab-separated record per emoji keeps the shipped module far smaller than
// an array of objects; the client splits it once on load.
const body = kept
  .map(
    (entry) =>
      `  [\n    ${JSON.stringify(entry.name)},\n    ${JSON.stringify(
        entry.emoji.map((emoji) => emoji.join("\t")).join("\n"),
      )},\n  ],`,
  )
  .join("\n");
const out = fileURLToPath(
  new URL("../internal/api/web/emoji-data.mjs", import.meta.url),
);
writeFileSync(
  out,
  `// Generated by tools/gen-emoji.mjs from Unicode emoji-test.txt (through E${MAX_VERSION})
// and the CLDR English annotations. Do not edit by hand.
// Each group holds newline-separated "emoji\\tname\\tsearch terms" records.
export const EMOJI_GROUPS = [
${body}
];
`,
);
console.log(`${out}: ${total} emoji in ${kept.length} groups`);
